export const HTTP_STATUS_CODE = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
};

export const HTTP_METHOD = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
};

export const SYSTEM_FORMAT_DATA = {
  DATE_FORMAT: 'DD/MM/YYYY',
  DATE_TIME_FORMAT: 'DD/MM/YYYY HH:mm:ss',
  MONTH_TIME_FORMAT: 'MM/YYYY',
  DATE_FORMAT_MILLISECONDS: 'YYYYMMDDHHmmssSSS',
  EMAIL_FORMAT: '[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-]+',
  PHONE_FORMAT: '^[ ]*((\\84)|0)([0-9]{9,10})[ ]*',
  FLOAT_FORMAT: '[^.]*([.](.{1,2}))?',
  NUMBER_FORMAT: '[^.]+',
};

export const TABLE_CONFIG = {
  DEFAULT_PAGE_INDEX: 0,
  DEFAULT_PAGE_SIZE: 20,
  DEFAULT_ORDER_DIRECTION: 'DESC',
};

export const SHOW_HEADER = 'show header';

export const SEARCH_OPERATOR = {
  GREATER_THAN: 'GREATER_THAN',
  LESS_THAN: 'LESS_THAN',
  GREATER_THAN_EQUAL: 'GREATER_THAN_EQUAL',
  LESS_THAN_EQUAL: 'LESS_THAN_EQUAL',
  NOT_EQUAL: 'NOT_EQUAL',
  EQUAL: 'EQUAL',
  MATCH: 'MATCH',
  IN: 'IN',
  DATE_GREATER_THAN: 'DATE_GREATER_THAN',
  DATE_LESS_THAN: 'DATE_LESS_THAN',
  DATE_GREATER_THAN_EQUAL: 'DATE_GREATER_THAN_EQUAL',
  DATE_LESS_THAN_EQUAL: 'DATE_LESS_THAN_EQUAL',
  DATE_EQUAL: 'DATE_EQUAL',
  DATE_MATCH: 'DATE_MATCH',
  BETWEEN: 'BETWEEN',
};
